# fly.toml file generated for art-expert-collmach-bot on 2023-04-15T00:19:11+03:00

app = "art-expert-collmach-bot"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "ams"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
